name: CI

on:
  push:
    branches:
      - main
      - test/storybook-test1
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test:nowatch -- --watchAll=false

      - name: Lint
        run: npm run lint

      - name: Build Package
        run: npm run build:package

      - name: Build Storybook
        run: npm run build-storybook
